C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\2N_Smolen_Leveled-S.pbn --ARCHIVE_FILE P:\bba\2N_Smolen_Leveled --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_2-Suited_Overcalls-S.pbn --ARCHIVE_FILE P:\bba\Opps_2-Suited_Overcalls --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\SCS_1C_any_0-4_Resp-S.pbn --ARCHIVE_FILE P:\bba\SCS_1C_any_0-4_Resp --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Splinters-S.pbn --ARCHIVE_FILE P:\bba\Splinters --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\SCS_1C_3-Suit_Resp_5-7-S.pbn --ARCHIVE_FILE P:\bba\SCS_1C_3-Suit_Resp_5-7 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Soloway_Jump_Shift-Type-1-S.pbn --ARCHIVE_FILE P:\bba\Soloway_Jump_Shift-Type-1 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\SCS_1C_any_5-7_Resp-S.pbn --ARCHIVE_FILE P:\bba\SCS_1C_any_5-7_Resp --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Two-Way_New_Minor_Forcing_aka_xyNT-N.pbn --ARCHIVE_FILE P:\bba\Two-Way_New_Minor_Forcing_aka_xyNT --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Misfit_11-12-S.pbn --ARCHIVE_FILE P:\bba\Misfit_11-12 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Stayman-N.pbn --ARCHIVE_FILE P:\bba\Stayman --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\After_1M_2M-S.pbn --ARCHIVE_FILE P:\bba\After_1M_2M --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Soloway_Jump_Shift-Type-3-S.pbn --ARCHIVE_FILE P:\bba\Soloway_Jump_Shift-Type-3 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Trap_Pass_Maybe.pbn --ARCHIVE_FILE P:\bba\Trap_Pass_May --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Splinters_By_Opener-S.pbn --ARCHIVE_FILE P:\bba\Splinters_By_Opener --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Minor_Slams-S.pbn --ARCHIVE_FILE P:\bba\Minor_Slams --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Trap_Pass-N.pbn --ARCHIVE_FILE P:\bba\Trap_Pass --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Two_Notrump-S.pbn --ARCHIVE_FILE P:\bba\Two_Notrump --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Preemptive_Overcall-N.pbn --ARCHIVE_FILE P:\bba\Opps_Preemptive_Overcall --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Jacoby_Transfer-S.pbn --ARCHIVE_FILE P:\bba\Jacoby_Transfer --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Ned_Weak_Two_Leveled-S.pbn --ARCHIVE_FILE P:\bba\Ned_Weak_Two_Leveled --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Any_5422_with_15-17-S.pbn --ARCHIVE_FILE P:\bba\Any_5422_with_15-17 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Vics_2C_Relay-S.pbn --ARCHIVE_FILE P:\bba\Vics_2C_Relay --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Slam_after_Stayman_or_Jacoby_w30plus-S.pbn --ARCHIVE_FILE P:\bba\Slam_after_Stayman_or_Jacoby_w30plus --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Open_1N_15-17-E.pbn --ARCHIVE_FILE P:\bba\Opps_Open_1N_15-17 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Slam_after_Transfer-S.pbn --ARCHIVE_FILE P:\bba\Slam_after_Transfer --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Multi_2D-S.pbn --ARCHIVE_FILE P:\bba\Multi_2D --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Tislevoll_after_Opps_Preempt-N.pbn --ARCHIVE_FILE P:\bba\Tislevoll_after_Opps_Preempt --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Minor_Suit_Opener-S.pbn --ARCHIVE_FILE P:\bba\Minor_Suit_Opener --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Overcalls-E.pbn --ARCHIVE_FILE P:\bba\Overcalls --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\We_Overcall_1N-E.pbn --ARCHIVE_FILE P:\bba\We_Overcall_1N --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_3_Under_Invitational_Jump-N.pbn --ARCHIVE_FILE P:\bba\Gavin_3_Under_Invitational_Jump --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gambling_3N-S.pbn --ARCHIVE_FILE P:\bba\Gambling_3N --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Weak_Two-E.pbn --ARCHIVE_FILE P:\bba\Opps_Weak_Two --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Reverse_After_Two_Over_One-S.pbn --ARCHIVE_FILE P:\bba\Reverse_After_Two_Over_One --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\McCabe_After_Weak_2-S.pbn --ARCHIVE_FILE P:\bba\McCabe_After_Weak_2 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Minor_Suit_Stayman-N.pbn --ARCHIVE_FILE P:\bba\Minor_Suit_Stayman --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\XYZ-S.pbn --ARCHIVE_FILE P:\bba\XYZ --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Jump_Overcalls-E.pbn --ARCHIVE_FILE P:\bba\Jump_Overcalls --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Weak_NT_10-12-S.pbn --ARCHIVE_FILE P:\bba\Weak_NT_10-12 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Negative_Double-S.pbn --ARCHIVE_FILE P:\bba\Negative_Double --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\3_Under_Invitational_Jump-S.pbn --ARCHIVE_FILE P:\bba\3_Under_Invitational_Jump --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Misfit_06-10-S.pbn --ARCHIVE_FILE P:\bba\Misfit_06-10 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Misfit_13-Plus-S.pbn --ARCHIVE_FILE P:\bba\Misfit_13-Plus --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\W2_X_XX-E.pbn --ARCHIVE_FILE P:\bba\W2_X_XX --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Namyats_Strong-S.pbn --ARCHIVE_FILE P:\bba\Namyats_Strong --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gerber_after_NT-S.pbn --ARCHIVE_FILE P:\bba\Gerber_after_NT --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\2N_Smolen-S.pbn --ARCHIVE_FILE P:\bba\2N_Smolen --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Transfers_after_1M_X-N.pbn --ARCHIVE_FILE P:\bba\Transfers_after_1M_X --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\2N_and_Balanced-S.pbn --ARCHIVE_FILE P:\bba\2N_and_Balanced --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Rule_of_16-18-N.pbn --ARCHIVE_FILE P:\bba\Rule_of_16-18 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Reverse_By_Opener-S.pbn --ARCHIVE_FILE P:\bba\Reverse_By_Opener --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Double_Showing_2_Suits-W.pbn --ARCHIVE_FILE P:\bba\Double_Showing_2_Suits --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Soloway_Jump_Shift-Type-2-S.pbn --ARCHIVE_FILE P:\bba\Soloway_Jump_Shift-Type-2 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_Semi-Constructive_Raise-N.pbn --ARCHIVE_FILE P:\bba\Gavin_Semi-Constructive_Raise --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\DONT-E.pbn --ARCHIVE_FILE P:\bba\DONT --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_Passed_Hand_Response_Structure-S.pbn --ARCHIVE_FILE P:\bba\Gavin_Passed_Hand_Response_Structure --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\We_X_Opps_Preempt-E.pbn --ARCHIVE_FILE P:\bba\We_X_Opps_Preempt --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Mitchell_Stayman-S.pbn --ARCHIVE_FILE P:\bba\Mitchell_Stayman --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\We_X_Opps_Weak_2-E.pbn --ARCHIVE_FILE P:\bba\We_X_Opps_Weak_2 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Going_for_Blood-S.pbn --ARCHIVE_FILE P:\bba\Going_for_Blood --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\3N_over_LHO_3x-W.pbn --ARCHIVE_FILE P:\bba\3N_over_LHO_3x --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Two-Way_Size_Ask-N.pbn --ARCHIVE_FILE P:\bba\Two-Way_Size_Ask --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Namyats_Weak-S.pbn --ARCHIVE_FILE P:\bba\Namyats_Weak --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Slam_after_Stayman-S.pbn --ARCHIVE_FILE P:\bba\Slam_after_Stayman --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_Transfers_after_2N_Rebid_Weak-N.pbn --ARCHIVE_FILE P:\bba\Gavin_Transfers_after_2N_Rebid_Weak --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\1N_GIB-S.pbn --ARCHIVE_FILE P:\bba\1N_GIB --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Ned_3-Level_Resp_to_1N-S.pbn --ARCHIVE_FILE P:\bba\Ned_3-Level_Resp_to_1N --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\SCS_Two_Clubs-S.pbn --ARCHIVE_FILE P:\bba\SCS_Two_Clubs --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Takeout_X-S.pbn --ARCHIVE_FILE P:\bba\Opps_Takeout_X --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Jordan_2N-S.pbn --ARCHIVE_FILE P:\bba\Jordan_2N --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\After_Opp_Overcalls-S.pbn --ARCHIVE_FILE P:\bba\After_Opp_Overcalls --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_Mixed_Raise-N.pbn --ARCHIVE_FILE P:\bba\Gavin_Mixed_Raise --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Overcall_Stayman_or_Jacoby-S.pbn --ARCHIVE_FILE P:\bba\Opps_Overcall_Stayman_or_Jacoby --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Better_Minor_Lebensohl-E.pbn --ARCHIVE_FILE P:\bba\Better_Minor_Lebensohl --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Slam_after_NT-S.pbn --ARCHIVE_FILE P:\bba\Slam_after_NT --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Double_Jacoby-S.pbn --ARCHIVE_FILE P:\bba\Opps_Double_Jacoby --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Dealing_with_Ovecalls_Strong-S.pbn --ARCHIVE_FILE P:\bba\Dealing_with_Ovecalls_Strong --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Overcall_1NT-S.pbn --ARCHIVE_FILE P:\bba\Opps_Overcall_1NT --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Lebensohl_Over_Weak_2-E.pbn --ARCHIVE_FILE P:\bba\Lebensohl_Over_Weak_2 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Trap_Pass_Maybe-N.pbn --ARCHIVE_FILE P:\bba\Trap_Pass_Maybe --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\After_Partner_Overcalls-E.pbn --ARCHIVE_FILE P:\bba\After_Partner_Overcalls --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Forcing_Pass-N.pbn --ARCHIVE_FILE P:\bba\Forcing_Pass --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Preempt_X_XX-E.pbn --ARCHIVE_FILE P:\bba\Preempt_X_XX --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Slam_after_Stayman_or_Jacoby_w31plus-S.pbn --ARCHIVE_FILE P:\bba\Slam_after_Stayman_or_Jacoby_w31plus --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Kokish_Relay-S.pbn --ARCHIVE_FILE P:\bba\Kokish_Relay --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Double_Stayman-S.pbn --ARCHIVE_FILE P:\bba\Opps_Double_Stayman --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Weak_NT_10-13-S.pbn --ARCHIVE_FILE P:\bba\Weak_NT_10-13 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Soloway_Jump_Shift-Type-4-S.pbn --ARCHIVE_FILE P:\bba\Soloway_Jump_Shift-Type-4 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Major_Suit_Fit-N.pbn --ARCHIVE_FILE P:\bba\Major_Suit_Fit --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_Semi-Forcing_NT_with_Fit-N.pbn --ARCHIVE_FILE P:\bba\Gavin_Semi-Forcing_NT_with_Fit --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Runout_after_1N_X-S.pbn --ARCHIVE_FILE P:\bba\Runout_after_1N_X --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Preempts-S.pbn --ARCHIVE_FILE P:\bba\Preempts --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Lebensohl-S.pbn --ARCHIVE_FILE P:\bba\Lebensohl --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\3N_over_RHO_3x-E.pbn --ARCHIVE_FILE P:\bba\3N_over_RHO_3x --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Two-Suited_Overcalls-E.pbn --ARCHIVE_FILE P:\bba\Two-Suited_Overcalls --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Jacoby_2N_4x_void-S.pbn --ARCHIVE_FILE P:\bba\Jacoby_2N_4x_void --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\2N_and_3C_Response-S.pbn --ARCHIVE_FILE P:\bba\2N_and_3C_Response --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Texas_or_Jacoby-N.pbn --ARCHIVE_FILE P:\bba\Texas_or_Jacoby --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Preempt-E.pbn --ARCHIVE_FILE P:\bba\Opps_Preempt --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\2N_and_MSS-S.pbn --ARCHIVE_FILE P:\bba\2N_and_MSS --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\SCS_1C_55_Resp-S.pbn --ARCHIVE_FILE P:\bba\SCS_1C_55_Resp --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Ned_Weak_Two-S.pbn --ARCHIVE_FILE P:\bba\Ned_Weak_Two --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Multi_2D-E.pbn --ARCHIVE_FILE P:\bba\Opps_Multi_2D --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_Weak_Splinter-N.pbn --ARCHIVE_FILE P:\bba\Gavin_Weak_Splinter --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Spiral_Raise-S.pbn --ARCHIVE_FILE P:\bba\Spiral_Raise --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Gambling_3N-E.pbn --ARCHIVE_FILE P:\bba\Opps_Gambling_3N --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\1m_1x_2m-S.pbn --ARCHIVE_FILE P:\bba\1m_1x_2m --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Rule_of_16-17-N.pbn --ARCHIVE_FILE P:\bba\Rule_of_16-17 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Bergen_Thrump_X_after_Preempt-N.pbn --ARCHIVE_FILE P:\bba\Bergen_Thrump_X_after_Preempt --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Non_Leaping_Michaels_After_3-Bid-E.pbn --ARCHIVE_FILE P:\bba\Non_Leaping_Michaels_After_3-Bid --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Weak_NT_14-15-S.pbn --ARCHIVE_FILE P:\bba\Weak_NT_14-15 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Bergen_Raises-N.pbn --ARCHIVE_FILE P:\bba\Bergen_Raises --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Jacoby_2N-S.pbn --ARCHIVE_FILE P:\bba\Jacoby_2N --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Rule_of_16-15-N.pbn --ARCHIVE_FILE P:\bba\Rule_of_16-15 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Takeout_X_We_XX-S.pbn --ARCHIVE_FILE P:\bba\Opps_Takeout_X_We_XX --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Notrump_18-19-N.pbn --ARCHIVE_FILE P:\bba\Notrump_18-19 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\New_Minor_Forcing-S.pbn --ARCHIVE_FILE P:\bba\New_Minor_Forcing --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Soloway_Jump_Shift-S.pbn --ARCHIVE_FILE P:\bba\Soloway_Jump_Shift --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Leaping_Michael-E.pbn --ARCHIVE_FILE P:\bba\Leaping_Michael --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Jacoby_Super-Accept-S.pbn --ARCHIVE_FILE P:\bba\Jacoby_Super-Accept --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Dealing_with_Overcalls_Weak-S.pbn --ARCHIVE_FILE P:\bba\Dealing_with_Overcalls_Weak --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\2N_Puppet_Leveled-S.pbn --ARCHIVE_FILE P:\bba\2N_Puppet_Leveled --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\1N_5M_and_6m-S.pbn --ARCHIVE_FILE P:\bba\1N_5M_and_6m --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_Transfers_after_2N_Rebid_Unb-N.pbn --ARCHIVE_FILE P:\bba\Gavin_Transfers_after_2N_Rebid_Unb --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\3N-S.pbn --ARCHIVE_FILE P:\bba\3N --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Weak_2_Bids_Leveled-S.pbn --ARCHIVE_FILE P:\bba\Weak_2_Bids_Leveled --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Reverse_By_Responder-S.pbn --ARCHIVE_FILE P:\bba\Reverse_By_Responder --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\SCS_Major_with_2nd_Suit-S.pbn --ARCHIVE_FILE P:\bba\SCS_Major_with_2nd_Suit --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Two_Over_One-S.pbn --ARCHIVE_FILE P:\bba\Two_Over_One --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Power_Double_Balanced-E.pbn --ARCHIVE_FILE P:\bba\Power_Double_Balanced --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Weak_NT_09-15-S.pbn --ARCHIVE_FILE P:\bba\Weak_NT_09-15 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Game_Overcalls-E.pbn --ARCHIVE_FILE P:\bba\Game_Overcalls --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\1N-S.pbn --ARCHIVE_FILE P:\bba\1N --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Robot_Free_Bid-N.pbn --ARCHIVE_FILE P:\bba\Robot_Free_Bid --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Game_Forcing_2C-S.pbn --ARCHIVE_FILE P:\bba\Game_Forcing_2C --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Ned_2S-N.pbn --ARCHIVE_FILE P:\bba\Ned_2S --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Weak_2_Bids_Lax_Leveled-S.pbn --ARCHIVE_FILE P:\bba\Weak_2_Bids_Lax_Leveled --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Power_Double_Unbalanced-E.pbn --ARCHIVE_FILE P:\bba\Power_Double_Unbalanced --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\2N_Puppet-S.pbn --ARCHIVE_FILE P:\bba\2N_Puppet --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_Transfers_after_2N_Rebid_Bal-N.pbn --ARCHIVE_FILE P:\bba\Gavin_Transfers_after_2N_Rebid_Bal --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\SCS_1C_3-Suit_Resp-S.pbn --ARCHIVE_FILE P:\bba\SCS_1C_3-Suit_Resp --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\2N_and_Transfers-S.pbn --ARCHIVE_FILE P:\bba\2N_and_Transfers --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Drury-S.pbn --ARCHIVE_FILE P:\bba\Drury --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Negative_Free_Bid-N.pbn --ARCHIVE_FILE P:\bba\Negative_Free_Bid --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opp_Redoubles-E.pbn --ARCHIVE_FILE P:\bba\Opp_Redoubles --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Weak_2_Bids_Lax-S.pbn --ARCHIVE_FILE P:\bba\Weak_2_Bids_Lax --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Spiral_Raises_with_3-S.pbn --ARCHIVE_FILE P:\bba\Spiral_Raises_with_3 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\2N_and_1_Minor-S.pbn --ARCHIVE_FILE P:\bba\2N_and_1_Minor --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Mixed_Raise_In_Comp-W.pbn --ARCHIVE_FILE P:\bba\Mixed_Raise_In_Comp --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\5431_After_NT-S.pbn --ARCHIVE_FILE P:\bba\5431_After_NT --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_3-Card_Limit_Raise-N.pbn --ARCHIVE_FILE P:\bba\Gavin_3-Card_Limit_Raise --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Jacoby_2N_4x_void_Leveled-S.pbn --ARCHIVE_FILE P:\bba\Jacoby_2N_4x_void_Leveled --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\2NT-S.pbn --ARCHIVE_FILE P:\bba\2NT --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Rule_of_2-W.pbn --ARCHIVE_FILE P:\bba\Rule_of_2 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Non_Leaping_Michaels_After_2-Bid-E.pbn --ARCHIVE_FILE P:\bba\Non_Leaping_Michaels_After_2-Bid --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Serious-N.pbn --ARCHIVE_FILE P:\bba\Serious --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Double_1_NT-S.pbn --ARCHIVE_FILE P:\bba\Opps_Double_1_NT --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Support_Double-S.pbn --ARCHIVE_FILE P:\bba\Support_Double --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Rule_of_16-N.pbn --ARCHIVE_FILE P:\bba\Rule_of_16 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Losing_Trick_Count-S.pbn --ARCHIVE_FILE P:\bba\Losing_Trick_Count --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Weak_NT_09-12-S.pbn --ARCHIVE_FILE P:\bba\Weak_NT_09-12 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_4-Card_Limit_Raise-N.pbn --ARCHIVE_FILE P:\bba\Gavin_4-Card_Limit_Raise --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\We_Overcall-E.pbn --ARCHIVE_FILE P:\bba\We_Overcall --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Misfit-S.pbn --ARCHIVE_FILE P:\bba\Misfit --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Inverted_Minors-S.pbn --ARCHIVE_FILE P:\bba\Inverted_Minors --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Trap_Pass.pbn --ARCHIVE_FILE P:\bba\Trap_Pa --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\SCS_1C_54_Resp-S.pbn --ARCHIVE_FILE P:\bba\SCS_1C_54_Resp --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Takeout_Double-E.pbn --ARCHIVE_FILE P:\bba\Takeout_Double --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Opps_Bid_Over_GF_2C-S.pbn --ARCHIVE_FILE P:\bba\Opps_Bid_Over_GF_2C --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Rule_of_16-16-N.pbn --ARCHIVE_FILE P:\bba\Rule_of_16-16 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\SCS_Major_Open_2-Suit_Resp-S.pbn --ARCHIVE_FILE P:\bba\SCS_Major_Open_2-Suit_Resp --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Texas_Transfer-N.pbn --ARCHIVE_FILE P:\bba\Texas_Transfer --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Good_Bad_2N-N.pbn --ARCHIVE_FILE P:\bba\Good_Bad_2N --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Gavin_Strong_Splinter-N.pbn --ARCHIVE_FILE P:\bba\Gavin_Strong_Splinter --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Major_Opener-S.pbn --ARCHIVE_FILE P:\bba\Major_Opener --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Responsive_Double-W.pbn --ARCHIVE_FILE P:\bba\Responsive_Double --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Smolen-S.pbn --ARCHIVE_FILE P:\bba\Smolen --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\1N_with_Singleton-S.pbn --ARCHIVE_FILE P:\bba\1N_with_Singleton --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Jacoby_2N_Leveled-S.pbn --ARCHIVE_FILE P:\bba\Jacoby_2N_Leveled --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Weak_2_Bids-S.pbn --ARCHIVE_FILE P:\bba\Weak_2_Bids --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Size_Asking_Minor_Suit_Stayman-N.pbn --ARCHIVE_FILE P:\bba\Size_Asking_Minor_Suit_Stayman --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Weak_NT_13-15-S.pbn --ARCHIVE_FILE P:\bba\Weak_NT_13-15 --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Meckwell-E.pbn --ARCHIVE_FILE P:\bba\Meckwell --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Splinters_After_Notrump-S.pbn --ARCHIVE_FILE P:\bba\Splinters_After_Notrump --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Two-Way_Game_Try-S.pbn --ARCHIVE_FILE P:\bba\Two-Way_Game_Try --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\SCS_1C_any_8plus_Resp-S.pbn --ARCHIVE_FILE P:\bba\SCS_1C_any_8plus_Resp --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Fourth_Suit_Forcing-S.pbn --ARCHIVE_FILE P:\bba\Fourth_Suit_Forcing --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\Multi_Landy-E.pbn --ARCHIVE_FILE P:\bba\Multi_Landy --AUTOCLOSE
C:\BBA\BBA --CC1 C:\BBA\GIB-ADB.bbsa --CC2 C:\BBA\GIB-Thorvald.bbsa --DD 0 --SD 1 --AUTOBID --HAND P:\pbn\McCabe_after_WJO-E.pbn --ARCHIVE_FILE P:\bba\McCabe_after_WJO --AUTOCLOSE
