P:\dealer P:\dlr\Dealer-3N-over-LHO-3x-W.dlr >P:\pbn\Dealer-3N-over-LHO-3x-W.pbn
P:\dealer P:\dlr\Dealer-Misfit-06-10-S.dlr >P:\pbn\Dealer-Misfit-06-10-S.pbn
P:\dealer P:\dlr\Dealer-Soloway-Jump-Shift-Type-4-S.dlr >P:\pbn\Dealer-Soloway-Jump-Shift-Type-4-S.pbn
P:\dealer P:\dlr\Dealer-DONT-E.dlr >P:\pbn\Dealer-DONT-E.pbn
P:\dealer P:\dlr\Dealer-Multi-2D-S.dlr >P:\pbn\Dealer-Multi-2D-S.pbn
P:\dealer P:\dlr\Dealer-Leaping-Michael-E.dlr >P:\pbn\Dealer-Leaping-Michael-E.pbn
P:\dealer P:\dlr\Dealer-Opps-Multi-2D-E.dlr >P:\pbn\Dealer-Opps-Multi-2D-E.pbn
P:\dealer P:\dlr\Dealer-Smolen-S.dlr >P:\pbn\Dealer-Smolen-S.pbn
P:\dealer P:\dlr\Dealer-TwoNotrump-S.dlr >P:\pbn\Dealer-TwoNotrump-S.pbn
P:\dealer P:\dlr\Dealer-2N-and-1-Minor-S.dlr >P:\pbn\Dealer-2N-and-1-Minor-S.pbn
P:\dealer P:\dlr\Dealer-Weak-NT-13-15-S.dlr >P:\pbn\Dealer-Weak-NT-13-15-S.pbn
P:\dealer P:\dlr\Dealer-Reverses-S.dlr >P:\pbn\Dealer-Reverses-S.pbn
P:\dealer P:\dlr\Dealer-Namyats-Strong-S.dlr >P:\pbn\Dealer-Namyats-Strong-S.pbn
P:\dealer P:\dlr\Dealer-Slam-after-Stayman-S.dlr >P:\pbn\Dealer-Slam-after-Stayman-S.pbn
P:\dealer P:\dlr\Gavin-Weak-Splinter-N.dlr >P:\pbn\Gavin-Weak-Splinter-N.pbn
P:\dealer P:\dlr\Dealer-TwoSuitedOvercalls-E.dlr >P:\pbn\Dealer-TwoSuitedOvercalls-E.pbn
P:\dealer P:\dlr\Basic-1-of-a-Minor-S.dlr >P:\pbn\Basic-1-of-a-Minor-S.pbn
P:\dealer P:\dlr\Dealer-Slam-after-Sta-Jac-2-S.dlr >P:\pbn\Dealer-Slam-after-Sta-Jac-2-S.pbn
P:\dealer P:\dlr\Dealer-Opps-Weak-Two-E.dlr >P:\pbn\Dealer-Opps-Weak-Two-E.pbn
P:\dealer P:\dlr\Dealer-Opps-Takeout-X-We-XX-S.dlr >P:\pbn\Dealer-Opps-Takeout-X-We-XX-S.pbn
P:\dealer P:\dlr\Dealer-Preempt-X-XX-E.dlr >P:\pbn\Dealer-Preempt-X-XX-E.pbn
P:\dealer P:\dlr\Dealer-Rule-of-16-16-N.dlr >P:\pbn\Dealer-Rule-of-16-16-N.pbn
P:\dealer P:\dlr\Basic-1-Notrump-Opening-S.dlr >P:\pbn\Basic-1-Notrump-Opening-S.pbn
P:\dealer P:\dlr\Dealer-Soloway-Jump-Shift-Type-2-S.dlr >P:\pbn\Dealer-Soloway-Jump-Shift-Type-2-S.pbn
P:\dealer P:\dlr\Dealer-Slam-after-Xfer-S.dlr >P:\pbn\Dealer-Slam-after-Xfer-S.pbn
P:\dealer P:\dlr\Dealer-VicsMajRespStr-S.dlr >P:\pbn\Dealer-VicsMajRespStr-S.pbn
P:\dealer P:\dlr\Dealer-Weak-NT-09-12-S.dlr >P:\pbn\Dealer-Weak-NT-09-12-S.pbn
P:\dealer P:\dlr\Dealer-W2-X-XX-E.dlr >P:\pbn\Dealer-W2-X-XX-E.pbn
P:\dealer P:\dlr\Dealer-Misfit-S.dlr >P:\pbn\Dealer-Misfit-S.pbn
P:\dealer P:\dlr\Dealer-Jacoby-2N-Leveled-S.dlr >P:\pbn\Dealer-Jacoby-2N-Leveled-S.pbn
P:\dealer P:\dlr\Dealer-1-Notrump-With-Singleton-S.dlr >P:\pbn\Dealer-1-Notrump-With-Singleton-S.pbn
P:\dealer P:\dlr\Dealer-We-Overcall-E.dlr >P:\pbn\Dealer-We-Overcall-E.pbn
P:\dealer P:\dlr\Dealer-Opps-Double-Stayman-S.dlr >P:\pbn\Dealer-Opps-Double-Stayman-S.pbn
P:\dealer P:\dlr\Dealer-Major-Suit-Fit-N.dlr >P:\pbn\Dealer-Major-Suit-Fit-N.pbn
P:\dealer P:\dlr\Dealer-Misfit-11-12-S.dlr >P:\pbn\Dealer-Misfit-11-12-S.pbn
P:\dealer P:\dlr\Dealer-SCS-1C-55_-Resp-S.dlr >P:\pbn\Dealer-SCS-1C-55_-Resp-S.pbn
P:\dealer P:\dlr\Dealer-3N-over-RHO-3x-E.dlr >P:\pbn\Dealer-3N-over-RHO-3x-E.pbn
P:\dealer P:\dlr\Dealer-Opps-Preemptive-Overcall-N.dlr >P:\pbn\Dealer-Opps-Preemptive-Overcall-N.pbn
P:\dealer P:\dlr\Basic-1-of-Any-Suit-S.dlr >P:\pbn\Basic-1-of-Any-Suit-S.pbn
P:\dealer P:\dlr\Dealer-Rule-of-2-W.dlr >P:\pbn\Dealer-Rule-of-2-W.pbn
P:\dealer P:\dlr\Gavin-3-card-Limit-Raise-N.dlr >P:\pbn\Gavin-3-card-Limit-Raise-N.pbn
P:\dealer P:\dlr\Dealer-Meckwell-E.dlr >P:\pbn\Dealer-Meckwell-E.pbn
P:\dealer P:\dlr\Dealer-2N-and-MSS-S.dlr >P:\pbn\Dealer-2N-and-MSS-S.pbn
P:\dealer P:\dlr\Gavin-3-Under-Invitational-Jump-N.dlr >P:\pbn\Gavin-3-Under-Invitational-Jump-N.pbn
P:\dealer P:\dlr\Gavin-PassedHandResponseStructure-S.dlr >P:\pbn\Gavin-PassedHandResponseStructure-S.pbn
P:\dealer P:\dlr\Gavin-Transfers-after-2N-Rebid-Unb-N.dlr >P:\pbn\Gavin-Transfers-after-2N-Rebid-Unb-N.pbn
P:\dealer P:\dlr\Dealer-Two-Way-Game-Try-S.dlr >P:\pbn\Dealer-Two-Way-Game-Try-S.pbn
P:\dealer P:\dlr\Dealer-SCS-1C-54-Resp-S.dlr >P:\pbn\Dealer-SCS-1C-54-Resp-S.pbn
P:\dealer P:\dlr\Dealer-Serious-N.dlr >P:\pbn\Dealer-Serious-N.pbn
P:\dealer P:\dlr\Dealer-XYZ-S.dlr >P:\pbn\Dealer-XYZ-S.pbn
P:\dealer P:\dlr\Gavin-4-card-Limit-Raise-N.dlr >P:\pbn\Gavin-4-card-Limit-Raise-N.pbn
P:\dealer P:\dlr\Basic-Stayman-N.dlr >P:\pbn\Basic-Stayman-N.pbn
P:\dealer P:\dlr\Dealer-Opps-Takeout-X-S.dlr >P:\pbn\Dealer-Opps-Takeout-X-S.pbn
P:\dealer P:\dlr\Dealer-Kokish-Relay-S.dlr >P:\pbn\Dealer-Kokish-Relay-S.pbn
P:\dealer P:\dlr\Dealer-Jump-Overcalls-E.dlr >P:\pbn\Dealer-Jump-Overcalls-E.pbn
P:\dealer P:\dlr\Dealer-Negative-Double-S.dlr >P:\pbn\Dealer-Negative-Double-S.pbn
P:\dealer P:\dlr\Dealer-Weak-2-Bids-S.dlr >P:\pbn\Dealer-Weak-2-Bids-S.pbn
P:\dealer P:\dlr\Basic-Responding-to-1-Minor-N.dlr >P:\pbn\Basic-Responding-to-1-Minor-N.pbn
P:\dealer P:\dlr\Dealer-Better-Minor-Lebensohl-E.dlr >P:\pbn\Dealer-Better-Minor-Lebensohl-E.pbn
P:\dealer P:\dlr\Dealer-Weak-NT-09-15-S.dlr >P:\pbn\Dealer-Weak-NT-09-15-S.pbn
P:\dealer P:\dlr\Dealer-McCabe-after-WJO-E.dlr >P:\pbn\Dealer-McCabe-after-WJO-E.pbn
P:\dealer P:\dlr\Dealer-Jordan-2N-S.dlr >P:\pbn\Dealer-Jordan-2N-S.pbn
P:\dealer P:\dlr\Dealer-Double-Showing-2-Suits-W.dlr >P:\pbn\Dealer-Double-Showing-2-Suits-W.pbn
P:\dealer P:\dlr\Dealer-2N-Puppet-Leveled-S.dlr >P:\pbn\Dealer-2N-Puppet-Leveled-S.pbn
P:\dealer P:\dlr\Dealer-2N-Smolen-S.dlr >P:\pbn\Dealer-2N-Smolen-S.pbn
P:\dealer P:\dlr\Dealer-Spiral-Raises-with-3-S.dlr >P:\pbn\Dealer-Spiral-Raises-with-3-S.pbn
P:\dealer P:\dlr\Dealer-Opps-Overcall-StaymanJacoby-S.dlr >P:\pbn\Dealer-Opps-Overcall-StaymanJacoby-S.pbn
P:\dealer P:\dlr\Dealer-SplintersByOpener-S.dlr >P:\pbn\Dealer-SplintersByOpener-S.pbn
P:\dealer P:\dlr\Dealer-Multi-Landy-E.dlr >P:\pbn\Dealer-Multi-Landy-E.pbn
P:\dealer P:\dlr\Dealer-Trap-Pass-Maybe-N.dlr >P:\pbn\Dealer-Trap-Pass-Maybe-N.pbn
P:\dealer P:\dlr\Basic-Jacoby-Transfer-N.dlr >P:\pbn\Basic-Jacoby-Transfer-N.pbn
P:\dealer P:\dlr\Gavin-Transfers-after-2N-Rebid-Bal-N.dlr >P:\pbn\Gavin-Transfers-after-2N-Rebid-Bal-N.pbn
P:\dealer P:\dlr\Dealer-Rule-of-16-15-N.dlr >P:\pbn\Dealer-Rule-of-16-15-N.pbn
P:\dealer P:\dlr\Dealer-SCS-1C-3-Suit-Resp-5-7-S.dlr >P:\pbn\Dealer-SCS-1C-3-Suit-Resp-5-7-S.pbn
P:\dealer P:\dlr\Dealer-Weak-NT-14-15-S.dlr >P:\pbn\Dealer-Weak-NT-14-15-S.pbn
P:\dealer P:\dlr\Dealer-Soloway-Jump-Shift-Type-1-S.dlr >P:\pbn\Dealer-Soloway-Jump-Shift-Type-1-S.pbn
P:\dealer P:\dlr\Basic-Major-Suit-Fit-N.dlr >P:\pbn\Basic-Major-Suit-Fit-N.pbn
P:\dealer P:\dlr\Dealer-Soloway-Jump-Shift-Type-3-S.dlr >P:\pbn\Dealer-Soloway-Jump-Shift-Type-3-S.pbn
P:\dealer P:\dlr\Dealer-Mitchell-Stayman-S.dlr >P:\pbn\Dealer-Mitchell-Stayman-S.pbn
P:\dealer P:\dlr\Dealer-Rule-of-16-17-N.dlr >P:\pbn\Dealer-Rule-of-16-17-N.pbn
P:\dealer P:\dlr\Dealer-2N-and-Balanced-S.dlr >P:\pbn\Dealer-2N-and-Balanced-S.pbn
P:\dealer P:\dlr\Dealer-Size-Asking-Minor-Suit-Stayman-N.dlr >P:\pbn\Dealer-Size-Asking-Minor-Suit-Stayman-N.pbn
P:\dealer P:\dlr\Basic-1-of-a-Major-S.dlr >P:\pbn\Basic-1-of-a-Major-S.pbn
P:\dealer P:\dlr\Dealer-Two-Way-New-Minor-Forcing-aka-xyNT-N.dlr >P:\pbn\Dealer-Two-Way-New-Minor-Forcing-aka-xyNT-N.pbn
P:\dealer P:\dlr\Dealer-SCS-Major-with-2nd-Suit-S.dlr >P:\pbn\Dealer-SCS-Major-with-2nd-Suit-S.pbn
P:\dealer P:\dlr\Dealer-Responsive-Double-W.dlr >P:\pbn\Dealer-Responsive-Double-W.pbn
P:\dealer P:\dlr\Gavin-Mixed-Raise-N.dlr >P:\pbn\Gavin-Mixed-Raise-N.pbn
P:\dealer P:\dlr\Dealer-Stayman-N.dlr >P:\pbn\Dealer-Stayman-N.pbn
P:\dealer P:\dlr\Dealer-MixedRiaseInComp-W.dlr >P:\pbn\Dealer-MixedRiaseInComp-W.pbn
P:\dealer P:\dlr\Dealer-Soloway-Jump-Shift-S.dlr >P:\pbn\Dealer-Soloway-Jump-Shift-S.pbn
P:\dealer P:\dlr\Dealer-Trap-Pass-N.dlr >P:\pbn\Dealer-Trap-Pass-N.pbn
P:\dealer P:\dlr\Dealer-Minor-Slams-S.dlr >P:\pbn\Dealer-Minor-Slams-S.pbn
P:\dealer P:\dlr\Dealer-Tislevoll-after-Opps-Preempt-N.dlr >P:\pbn\Dealer-Tislevoll-after-Opps-Preempt-N.pbn
P:\dealer P:\dlr\Dealer-Going-for-Blood-S.dlr >P:\pbn\Dealer-Going-for-Blood-S.pbn
P:\dealer P:\dlr\Dealer-Texas-or-Jacoby-N.dlr >P:\pbn\Dealer-Texas-or-Jacoby-N.pbn
P:\dealer P:\dlr\Dealer-Splinters-S.dlr >P:\pbn\Dealer-Splinters-S.pbn
P:\dealer P:\dlr\Dealer-SCS-1C-3-Suit-Resp-S.dlr >P:\pbn\Dealer-SCS-1C-3-Suit-Resp-S.pbn
P:\dealer P:\dlr\Dealer-Gerber-after-NT-S.dlr >P:\pbn\Dealer-Gerber-after-NT-S.pbn
P:\dealer P:\dlr\Dealer-Slam-after-Stayman-or-Jacoby-S.dlr >P:\pbn\Dealer-Slam-after-Stayman-or-Jacoby-S.pbn
P:\dealer P:\dlr\Dealer-Rule-of-16-N.dlr >P:\pbn\Dealer-Rule-of-16-N.pbn
P:\dealer P:\dlr\Dealer-Weak-NT-10-13-S.dlr >P:\pbn\Dealer-Weak-NT-10-13-S.pbn
P:\dealer P:\dlr\Dealer-TwoOverOne-S.dlr >P:\pbn\Dealer-TwoOverOne-S.pbn
P:\dealer P:\dlr\Dealer-1-Notrump-S.dlr >P:\pbn\Dealer-1-Notrump-S.pbn
P:\dealer P:\dlr\Dealer-Namyats-Weak-S.dlr >P:\pbn\Dealer-Namyats-Weak-S.pbn
P:\dealer P:\dlr\Dealer-3-Under-Invitational-Jump-S.dlr >P:\pbn\Dealer-3-Under-Invitational-Jump-S.pbn
P:\dealer P:\dlr\Dealer-Jacoby-2N-S.dlr >P:\pbn\Dealer-Jacoby-2N-S.pbn
P:\dealer P:\dlr\Dealer-Opps-Preempt-E.dlr >P:\pbn\Dealer-Opps-Preempt-E.pbn
P:\dealer P:\dlr\Dealer-Dealing-with-Overcalls-Weak-S.dlr >P:\pbn\Dealer-Dealing-with-Overcalls-Weak-S.pbn
P:\dealer P:\dlr\Dealer-Negative-Free-Bid-N.dlr >P:\pbn\Dealer-Negative-Free-Bid-N.pbn
P:\dealer P:\dlr\Dealer-We-Overcall-1N-E.dlr >P:\pbn\Dealer-We-Overcall-1N-E.pbn
P:\dealer P:\dlr\Dealer-Jacoby-2N-4x-void-S.dlr >P:\pbn\Dealer-Jacoby-2N-4x-void-S.pbn
P:\dealer P:\dlr\Dealer-SCS-1C-any-0-4-Resp-S.dlr >P:\pbn\Dealer-SCS-1C-any-0-4-Resp-S.pbn
P:\dealer P:\dlr\Dealer-Opps-Overcall-1NT-S.dlr >P:\pbn\Dealer-Opps-Overcall-1NT-S.pbn
P:\dealer P:\dlr\Basic-All-NT-Responses-N.dlr >P:\pbn\Basic-All-NT-Responses-N.pbn
P:\dealer P:\dlr\Dealer-Opps-Double-1-NT-S.dlr >P:\pbn\Dealer-Opps-Double-1-NT-S.pbn
P:\dealer P:\dlr\Dealer-Transfers-after-1M-X-N.dlr >P:\pbn\Dealer-Transfers-after-1M-X-N.pbn
P:\dealer P:\dlr\Dealer-Texas-Transfer-N.dlr >P:\pbn\Dealer-Texas-Transfer-N.pbn
P:\dealer P:\dlr\Dealer-SCS-1C-any-5-7-Resp-S.dlr >P:\pbn\Dealer-SCS-1C-any-5-7-Resp-S.pbn
P:\dealer P:\dlr\Dealer-Overcalls-E.dlr >P:\pbn\Dealer-Overcalls-E.pbn
P:\dealer P:\dlr\Dealer-Minor-Suit-Opener-S.dlr >P:\pbn\Dealer-Minor-Suit-Opener-S.pbn
P:\dealer P:\dlr\Dealer-Weak-2-Bids-Leveled-S.dlr >P:\pbn\Dealer-Weak-2-Bids-Leveled-S.pbn
P:\dealer P:\dlr\A-Test-File-N.dlr >P:\pbn\A-Test-File-N.pbn
P:\dealer P:\dlr\Dealer-Jacoby-2N-4x-void-Leveled-S.dlr >P:\pbn\Dealer-Jacoby-2N-4x-void-Leveled-S.pbn
P:\dealer P:\dlr\Dealer-Lebensohl-Over-Weak-2-E.dlr >P:\pbn\Dealer-Lebensohl-Over-Weak-2-E.pbn
P:\dealer P:\dlr\Dealer-SCS-Two-Clubs-S.dlr >P:\pbn\Dealer-SCS-Two-Clubs-S.pbn
P:\dealer P:\dlr\Dealer-2NT-S.dlr >P:\pbn\Dealer-2NT-S.pbn
P:\dealer P:\dlr\Dealer-3N-S.dlr >P:\pbn\Dealer-3N-S.pbn
P:\dealer P:\dlr\Dealer-Spiral-Raise-S.dlr >P:\pbn\Dealer-Spiral-Raise-S.pbn
P:\dealer P:\dlr\Dealer-Inverted-Minors-S.dlr >P:\pbn\Dealer-Inverted-Minors-S.pbn
P:\dealer P:\dlr\Dealer-Opp-Redoubles-E.dlr >P:\pbn\Dealer-Opp-Redoubles-E.pbn
P:\dealer P:\dlr\Dealer-Preempts-S.dlr >P:\pbn\Dealer-Preempts-S.pbn
P:\dealer P:\dlr\Dealer-Rule-of-16-18-N.dlr >P:\pbn\Dealer-Rule-of-16-18-N.pbn
P:\dealer P:\dlr\Dealer-New-Minor-Forcing-S.dlr >P:\pbn\Dealer-New-Minor-Forcing-S.pbn
P:\dealer P:\dlr\Basic-Other-NT-Response-N.dlr >P:\pbn\Basic-Other-NT-Response-N.pbn
P:\dealer P:\dlr\Dealer-Minor-Suit-Stayman-N.dlr >P:\pbn\Dealer-Minor-Suit-Stayman-N.pbn
P:\dealer P:\dlr\Dealer-Power-Double-Unbalanced-E.dlr >P:\pbn\Dealer-Power-Double-Unbalanced-E.pbn
P:\dealer P:\dlr\Dealer-Gambling-3N-S.dlr >P:\pbn\Dealer-Gambling-3N-S.pbn
P:\dealer P:\dlr\Dealer-Major-Opener-S.dlr >P:\pbn\Dealer-Major-Opener-S.pbn
P:\dealer P:\dlr\Dealer-Opps-2-Suited-Overcalls-S.dlr >P:\pbn\Dealer-Opps-2-Suited-Overcalls-S.pbn
P:\dealer P:\dlr\Dealer-1N-5Mand6-m-S.dlr >P:\pbn\Dealer-1N-5Mand6-m-S.pbn
P:\dealer P:\dlr\Gavin-Strong-Splinter-N.dlr >P:\pbn\Gavin-Strong-Splinter-N.pbn
P:\dealer P:\dlr\Dealer-Bergen-Thrump-X-after-Preempt-N.dlr >P:\pbn\Dealer-Bergen-Thrump-X-after-Preempt-N.pbn
P:\dealer P:\dlr\Dealer-Weak-NT-10-12-S.dlr >P:\pbn\Dealer-Weak-NT-10-12-S.pbn
P:\dealer P:\dlr\Dealer-SCS-1C-any-8-Plus-Resp-S.dlr >P:\pbn\Dealer-SCS-1C-any-8-Plus-Resp-S.pbn
P:\dealer P:\dlr\Gavin-Semi-Constructive-Raise-N.dlr >P:\pbn\Gavin-Semi-Constructive-Raise-N.pbn
P:\dealer P:\dlr\Dealer-SCS-Major-Open-2-Suit-Resp-S.dlr >P:\pbn\Dealer-SCS-Major-Open-2-Suit-Resp-S.pbn
P:\dealer P:\dlr\Dealer-Weak-2-Bids-Lax-Leveled-S.dlr >P:\pbn\Dealer-Weak-2-Bids-Lax-Leveled-S.pbn
P:\dealer P:\dlr\Gavin-Semi-Forcing-NT-with-Fit-N.dlr >P:\pbn\Gavin-Semi-Forcing-NT-with-Fit-N.pbn
P:\dealer P:\dlr\Dealer-Game-Forcing-2C-S.dlr >P:\pbn\Dealer-Game-Forcing-2C-S.pbn
P:\dealer P:\dlr\Dealer-FourthSuitForcing-S.dlr >P:\pbn\Dealer-FourthSuitForcing-S.pbn
P:\dealer P:\dlr\Dealer-Ned-2S-N.dlr >P:\pbn\Dealer-Ned-2S-N.pbn
P:\dealer P:\dlr\Dealer-Slam-after-NT-S.dlr >P:\pbn\Dealer-Slam-after-NT-S.pbn
P:\dealer P:\dlr\Dealer-After1M-2M-S.dlr >P:\pbn\Dealer-After1M-2M-S.pbn
P:\dealer P:\dlr\Dealer-Bergen-Raises-N.dlr >P:\pbn\Dealer-Bergen-Raises-N.pbn
P:\dealer P:\dlr\Dealer-Opps-Double-Jacoby-S.dlr >P:\pbn\Dealer-Opps-Double-Jacoby-S.pbn
P:\dealer P:\dlr\Dealer-Misfit-13-Plus-S.dlr >P:\pbn\Dealer-Misfit-13-Plus-S.pbn
P:\dealer P:\dlr\Dealer-Support-Double-S.dlr >P:\pbn\Dealer-Support-Double-S.pbn
P:\dealer P:\dlr\Dealer-Opps-Gambling-3N-E.dlr >P:\pbn\Dealer-Opps-Gambling-3N-E.pbn
P:\dealer P:\dlr\Gavin-Transfers-after-2N-Rebid-Weak-N.dlr >P:\pbn\Gavin-Transfers-after-2N-Rebid-Weak-N.pbn
P:\dealer P:\dlr\Dealer-Weak-2-Bids-Lax-S.dlr >P:\pbn\Dealer-Weak-2-Bids-Lax-S.pbn
P:\dealer P:\dlr\Dealer-Ned-Weak-Two-S.dlr >P:\pbn\Dealer-Ned-Weak-Two-S.pbn
P:\dealer P:\dlr\Dealer-2N-and-3C-Response-S.dlr >P:\pbn\Dealer-2N-and-3C-Response-S.pbn
P:\dealer P:\dlr\Dealer-Runout-after-1N-X-S.dlr >P:\pbn\Dealer-Runout-after-1N-X-S.pbn
P:\dealer P:\dlr\Dealer-Non-Leaping-Michaels-After-2Bid-E.dlr >P:\pbn\Dealer-Non-Leaping-Michaels-After-2Bid-E.pbn
P:\dealer P:\dlr\Dealer-Non-Leaping-Michaels-After-3Bid-E.dlr >P:\pbn\Dealer-Non-Leaping-Michaels-After-3Bid-E.pbn
P:\dealer P:\dlr\Dealer-Lebensohl-S.dlr >P:\pbn\Dealer-Lebensohl-S.pbn
P:\dealer P:\dlr\Dealer-Dealing-with-Ovecalls-Strong-S.dlr >P:\pbn\Dealer-Dealing-with-Ovecalls-Strong-S.pbn
P:\dealer P:\dlr\Dealer-2N-Puppet-S.dlr >P:\pbn\Dealer-2N-Puppet-S.pbn
P:\dealer P:\dlr\Dealer-Power-Double-Balanced-E.dlr >P:\pbn\Dealer-Power-Double-Balanced-E.pbn
P:\dealer P:\dlr\Dealer-2N-and-Transfers-S.dlr >P:\pbn\Dealer-2N-and-Transfers-S.pbn
P:\dealer P:\dlr\Dealer-Ned-3-Level-Resp-to-1N-S.dlr >P:\pbn\Dealer-Ned-3-Level-Resp-to-1N-S.pbn
P:\dealer P:\dlr\Dealer-Takeout-Double-E.dlr >P:\pbn\Dealer-Takeout-Double-E.pbn
P:\dealer P:\dlr\Dealer-2N-Smolen-Leveled-S.dlr >P:\pbn\Dealer-2N-Smolen-Leveled-S.pbn
P:\dealer P:\dlr\Dealer-Robot-Free-Bid-N.dlr >P:\pbn\Dealer-Robot-Free-Bid-N.pbn
P:\dealer P:\dlr\Dealer-Two-Way-Size-Ask-N.dlr >P:\pbn\Dealer-Two-Way-Size-Ask-N.pbn
P:\dealer P:\dlr\Dealer-Notrump-18-19-N.dlr >P:\pbn\Dealer-Notrump-18-19-N.pbn
P:\dealer P:\dlr\Dealer-Drury-S.dlr >P:\pbn\Dealer-Drury-S.pbn
P:\dealer P:\dlr\Dealer-McCabe-After-Weak-2-S.dlr >P:\pbn\Dealer-McCabe-After-Weak-2-S.pbn
# Scan complete!
