"""
HTML output formatter for PBN diff results.
"""

import html
from typing import List, Optional

from ..comparator import DiffResult, DiffType


class HTMLFormatter:
    """Format diff results as HTML report."""

    HTML_TEMPLATE = '''<!DOCTYPE html>
<html>
<head>
    <title>PBN Comparison Report</title>
    <meta charset="utf-8">
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            margin: 20px;
            background: #fafafa;
        }}
        h1 {{
            color: #333;
            border-bottom: 2px solid #007bff;
            padding-bottom: 10px;
        }}
        .summary {{
            background: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }}
        .summary table {{
            width: 100%;
            border-collapse: collapse;
        }}
        .summary th {{
            text-align: left;
            padding: 8px 12px;
            background: #f8f9fa;
            border-bottom: 1px solid #dee2e6;
            width: 200px;
        }}
        .summary td {{
            padding: 8px 12px;
            border-bottom: 1px solid #dee2e6;
        }}
        .diff-added {{
            background: #d4edda;
            border-left: 4px solid #28a745;
            padding: 12px 15px;
            margin: 10px 0;
            border-radius: 4px;
        }}
        .diff-removed {{
            background: #f8d7da;
            border-left: 4px solid #dc3545;
            padding: 12px 15px;
            margin: 10px 0;
            border-radius: 4px;
        }}
        .diff-modified {{
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 12px 15px;
            margin: 10px 0;
            border-radius: 4px;
        }}
        .board-header {{
            font-weight: bold;
            font-size: 1.1em;
            margin-bottom: 8px;
        }}
        .deal {{
            font-family: monospace;
            font-size: 0.9em;
            color: #666;
            word-break: break-all;
        }}
        .tag-diff {{
            margin: 8px 0 8px 20px;
            font-family: monospace;
            font-size: 0.95em;
        }}
        .value-old {{
            color: #dc3545;
            text-decoration: line-through;
        }}
        .value-new {{
            color: #28a745;
        }}
        .stat-modified {{ color: #856404; font-weight: bold; }}
        .stat-added {{ color: #155724; font-weight: bold; }}
        .stat-removed {{ color: #721c24; font-weight: bold; }}
        .no-diff {{
            text-align: center;
            padding: 40px;
            color: #28a745;
            font-size: 1.2em;
        }}
        footer {{
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #dee2e6;
            color: #6c757d;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <h1>PBN Comparison Report</h1>
    {content}
    <footer>
        Generated by pbn-diff.py
    </footer>
</body>
</html>'''

    def format(
        self, result: DiffResult, board_filter: Optional[List[int]] = None
    ) -> str:
        """Format complete HTML report."""
        content = []
        content.append(self._format_summary_html(result))
        content.append(self._format_differences_html(result, board_filter))
        return self.HTML_TEMPLATE.format(content="\n".join(content))

    def _format_summary_html(self, result: DiffResult) -> str:
        """Format summary section as HTML."""
        modified_class = ' class="stat-modified"' if result.modified_records else ""
        added_class = ' class="stat-added"' if result.added_records else ""
        removed_class = ' class="stat-removed"' if result.removed_records else ""

        matched_row = ""
        modified_row = ""
        if result.mode == "semantic":
            matched_row = f"<tr><th>Matched Records</th><td>{result.matched_records}</td></tr>"
            modified_row = f'<tr><th>Modified Records</th><td{modified_class}>{result.modified_records}</td></tr>'

        return f'''
        <div class="summary">
            <h2>Summary</h2>
            <table>
                <tr><th>File 1</th><td>{html.escape(result.file1_path)}</td></tr>
                <tr><th>File 2</th><td>{html.escape(result.file2_path)}</td></tr>
                <tr><th>Mode</th><td>{html.escape(result.mode)}</td></tr>
                <tr><th>Records in File 1</th><td>{result.total_records_file1}</td></tr>
                <tr><th>Records in File 2</th><td>{result.total_records_file2}</td></tr>
                {matched_row}
                {modified_row}
                <tr><th>Added Records</th><td{added_class}>{result.added_records}</td></tr>
                <tr><th>Removed Records</th><td{removed_class}>{result.removed_records}</td></tr>
            </table>
        </div>'''

    def _format_differences_html(
        self, result: DiffResult, board_filter: Optional[List[int]] = None
    ) -> str:
        """Format differences section as HTML."""
        if not result.record_differences:
            return '<div class="no-diff">No differences found.</div>'

        lines = ["<h2>Differences</h2>"]

        for diff in result.record_differences:
            # Apply board filter
            if board_filter and diff.board_number not in board_filter:
                continue

            css_class = {
                DiffType.ADDED: "diff-added",
                DiffType.REMOVED: "diff-removed",
                DiffType.MODIFIED: "diff-modified",
            }.get(diff.diff_type, "")

            type_label = diff.diff_type.value.upper()

            lines.append(f'<div class="{css_class}">')
            lines.append(
                f'<div class="board-header">Board {diff.board_number} ({type_label})</div>'
            )
            lines.append(f'<div class="deal">Deal: {html.escape(diff.deal)}</div>')

            for tag_diff in diff.tag_differences:
                if tag_diff.diff_type == DiffType.MODIFIED:
                    lines.append(
                        f'<div class="tag-diff">[{html.escape(tag_diff.tag_name)}]: '
                        f'<span class="value-old">{html.escape(str(tag_diff.value1))}</span> '
                        f'&rarr; '
                        f'<span class="value-new">{html.escape(str(tag_diff.value2))}</span></div>'
                    )
                elif tag_diff.diff_type == DiffType.ADDED:
                    lines.append(
                        f'<div class="tag-diff">+ [{html.escape(tag_diff.tag_name)}]: '
                        f'<span class="value-new">{html.escape(str(tag_diff.value2))}</span></div>'
                    )
                else:
                    lines.append(
                        f'<div class="tag-diff">- [{html.escape(tag_diff.tag_name)}]: '
                        f'<span class="value-old">{html.escape(str(tag_diff.value1))}</span></div>'
                    )

            lines.append("</div>")

        return "\n".join(lines)
