@ECHO OFF

SET Title=call P:\build-scripts\setOneTitle.cmd P:\bba-filtered\

%Title%1N.pbn									"1NT Opening Bids"
%Title%1N_5M_and_6m.pbn							"Responding to 1NT with a 5-card major and a 6-card minor"
%Title%1N_GIB.pbn								"1NT GIB (robot) Opening Bids"
%Title%1N_with_Singleton.pbn 					"Opening 1NT with a Singleton"
%Title%1m_1x_2m.pbn								"Opening 1m, responder bids a suit, and opener rebids 2m"
%Title%2NT.pbn 									"2NT Opening Bids"
%Title%2N_Smolen.pbn 							"Smolen after 2NT opener"
%Title%2N_Smolen_Leveled.pbn 					"Smolen after 2NT opener (leveled)"
%Title%2N_and_1_Minor.pbn						"Responding to 1NT wiht a long minor"
%Title%2N_and_3C_Response.pbn					"Puppet Stayman over 2NT"
%Title%2N_and_Balanced.pbn 						"Responding to 2NT with a balanced hand"
%Title%2N_and_Transfers.pbn						"Transfers to 2NT"
%Title%3N.pbn									"3NT Opening Bids (25+ balanced)
%Title%3N_over_LHO_3x.pbn						"Overcall 3NT over LHO weak 3 opener"
%Title%3N_over_RHO_3x.pbn						"Overcall 3NT over RHO weak 3 opener"
%Title%5431_After_NT.pbn 						"Responding to 1NT with 5431"
%Title%After_1M_2M.pbn 							"Opener's rebid after partner raises 1M to 2M"
%Title%After_Opp_Overcalls.pbn 					"Responding after RHO overcall's partner's opening bid"
%Title%After_Partner_Overcalls.pbn 				"Advancing after partner makes an overcall"
%Title%Any_5422_with_15-17.pbn 					"Opening with 15-17 HCP and any 5422 pattern"
%Title%Dealing_with_Ovecalls_Strong.pbn			"Dealing with Overcalls (strong hand)"
%Title%Dealing_with_Overcalls_Weak.pbn 			"Dealing with Overcalls (weak hand)"
%Title%Double_Showing_2_Suits.pbn				"Double showing 2 suits"
%Title%Drury.pbn 								"Reverse Drury"
%Title%Fourth_Suit_Forcing.pbn 					"Fourth Suit Forcing"
%Title%Gambling_3N.pbn 							"Gambling 3NT"
%Title%Game_Forcing_2C.pbn 						"Game Forcing 2C Opener"
%Title%Game_Overcalls.pbn						"Game Overcalls"
%Title%Gerber_By_Responder.pbn 					"Gerber by Responder"
%Title%Gerber_By_opener.pbn						"Gerber by Opener"
%Title%Inverted_Minors.pbn 						"Inverted Minors"
%Title%Jacoby_2N.pbn 							"Jacoby 2NT"
%Title%Jacoby_2N_4x_void.pbn 					"Jacoby 2NT with a void"
%Title%Jacoby_2N_4x_void_Leveled.pbn 			"Jacoby 2NT with a void (leveled)"
%Title%Jacoby_2N_Leveled.pbn 					"Jacoby 2NT (leveled)"
%Title%Jacoby_Super-Accept.pbn 					"Jacoby Transfer Superaccepts"
%Title%Jacoby_Transfer.pbn 						"Jacoby Transfers"
%Title%Jordan_2N.pbn 							"Jordan 2NT"
%Title%Jump_Overcalls.pbn						"Jump Overcalls"
%Title%Leaping_Michael.pbn 						"Leaping Michaels"
%Title%Lebensohl.pbn 							"Lebensohl after interference over partner's 1NT"
%Title%Lebensohl_Over_Weak_2.pbn 				"Lebensohl after double of weak 2"
%Title%Losing_Trick_Count.pbn					"Losing Trick Count"
%Title%Major_Opener.pbn							"Major Suit Openers"
%Title%Major_Suit_Fit.pbn						"Major Suit Fits"
%Title%Minor_Slams.pbn                          "Minor Suit Slams"                                            
%Title%Minor_Suit_Opener.pbn 					"Major Suit Openers"
%Title%Mixed_Raise_In_Comp.pbn 					"Major Raise In Competition"
%Title%Namyats_Strong.pbn						"Namyats (strong)"
%Title%Namyats_Weak.pbn							"Namyats (weak)"
%Title%Negative_Double.pbn 						"Negative Doubles"
%Title%New_Minor_Forcing.pbn 					"New Minor Forcing (over 1NT rebid by opener)"
%Title%Notrump_18-19.pbn 						"Balanced hand 18-19 HCP"
%Title%Opp_Redoubles.pbn 						"Opponent's Redouble"
%Title%Opps_2-Suited_Overcalls.pbn 				"Opponent's Two-Suited Overcalls"
%Title%Opps_Bid_Over_GF_2C.pbn 					"Opponents Bid Over GF 2C"
%Title%Opps_Double_1_NT.pbn						"Opponents Double our 1NT Opening Bid"
%Title%Opps_Double_Jacoby.pbn					"Opponents Double Jacoby Transfer"
%Title%Opps_Double_Stayman.pbn 					"Opponents Double Stayman"
%Title%Opps_Open_1N_15-17.pbn					"Opponents Open 1NT (15-17)"
%Title%Opps_Overcall_1NT.pbn 					"Opponents Overcall 1NT (15-18)"
%Title%Opps_Overcall_Stayman_or_Jacoby.pbn 		"Opponents Overcall Stayman or Jacoby"
%Title%Opps_Preempt.pbn							"Opponents Preepmt"
%Title%Opps_Preemptive_Overcall.pbn				"Opponents Preemptive Overcall"
%Title%Opps_Takeout_X.pbn						"Opponent's Takeout Double"
%Title%Opps_Takeout_X_We_XX.pbn					"Opponent's Takeout Double, we Redouble"
%Title%Opps_Weak_Two.pbn 						"Opponent's Weak Two"
%Title%Overcalls.pbn 							"Overcalls"
%Title%Power_Double_Balanced.pbn 				"Power Double Balanced"
%Title%Power_Double_Unbalanced.pbn 				"Power Double Unbalanced"
%Title%Preempt_X_XX.pbn							"Preempt Doubled then Redoubled"
%Title%Preempts.pbn								"Preepmts"
%Title%Responsive_Double.pbn 					"Responsive Double"
%Title%Reverse_After_Two_Over_One.pbn			"Reverse after Two Over One"
%Title%Reverse_By_Opener.pbn					"Reverse by Opener"
%Title%Reverse_By_Responder.pbn					"Reverse by Responder"
%Title%Rule_of_16-15.pbn 						"Rule of 16-15"
%Title%Rule_of_16-16.pbn 						"Rule of 16-16"
%Title%Rule_of_16-18.pbn 						"Rule of 16-18"
%Title%Rule_of_16.pbn							"Rule of 16"
%Title%Runout_after_1N_X.pbn 					"Runout After 1NT Double"
%Title%Slam_after_NT.pbn 						"Slam after 1NT Opener"
%Title%Slam_after_Stayman.pbn					"Slam after Stayman"
%Title%Slam_after_Stayman_or_Jacoby_w30plus.pbn "Slam after Stayman or Jacoby with 30+ Points"
%Title%Slam_after_Stayman_or_Jacoby_w31plus.pbn	"Slam after Stayman or Jacoby with 31+ Points"
%Title%Slam_after_Transfer.pbn 					"Slam after Transfer"
%Title%Smolen.pbn								"Smolen"
%Title%Splinters.pbn 							"Splinters"
%Title%Splinters_After_Notrump.pbn 				"Splinters after NT"
%Title%Splinters_By_Opener.pbn 					"Splinters by Opener"
%Title%Stayman.pbn 								"Stayman"
%Title%Support_Double.pbn						"Support Double"
%Title%Takeout_Double.pbn						"Takeout Double"
%Title%Texas_Transfer.pbn						"Texas Transfer"
%Title%Texas_or_Jacoby.pbn 						"Texas or Jacoby Transfers"
%Title%Two-Suited_Overcalls.pbn					"Two-Suited Overcalls"
%Title%Two-Way_Game_Try.pbn						"Two-Way Game Tries"
%Title%Two-Way_New_Minor_Forcing_aka_xyNT.pbn	"Two-Way New Minor Forcing"
%Title%Two_Notrump.pbn 							"2NT Openers"
%Title%Two_Over_One.pbn							"Two Over One Game Force"
%Title%W2_X_XX.pbn 								"Weak Two Opener, Doubled then Redoubled"
%Title%We_Overcall.pbn 							"We Overcall"
%Title%We_Overcall_1N.pbn						"We Overcall 1NT"
%Title%We_X_Opps_Preempt.pbn 					"We Double Opponents' Preempt"
%Title%We_X_Opps_Weak_2.pbn						"We Double Opponent's Weak Two Opener"
%Title%Weak_2_Bids.pbn 							"Weak Two Bids"
%Title%Weak_2_Bids_Lax.pbn 						"Weak Two Bids Lax"
%Title%Weak_2_Bids_Lax_Leveled.pbn 				"Weak Two Bids Lax (leveled)"
%Title%Weak_2_Bids_Leveled.pbn 					"Weak Two Bids (leveled)"